name: Deploy Java Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env

      - name: Build docker image
        run: |
          IMAGE_TAG=devhuynh2003/chatting-app:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: docker push ${{ env.IMAGE_TAG }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ env.IMAGE_TAG }}

      - name: Run new container
        run: |
          docker run -d -p 8080:8080 \
          -e SITE_URL=${{ secrets.SITE_URL }} \
          --name chatting-app-container-new \
          ${{ env.IMAGE_TAG }}

      - name: Check new container health
        run: |
          sleep 10 # Đợi container khởi động
          curl -f http://localhost:8080 || exit 1

      - name: Delete old container and switch
        run: |
          docker rm -f chatting-app-container || true
          docker rename chatting-app-container-new chatting-app-container
